//#pragma once
//#include "json.hpp"
//
//using json = nlohmann::json;
//
//
//json moduleMap = {
//	{ "Required", true },
//	{ "Spawn", true },
//	{ "Initial Size", false },
//	{ "Size By Scale", false },
//	{ "Size By Life", false },
//	{ "Size By Speed", false },
//	{ "Lifetime", false },
//	{ "Initial Color", false },
//	{ "Color Over Life", false },
//	{ "Color Scale Life", false },
//	{ "Initial Velocity", false },
//	{ "Velocity Cone", false },
//	{ "Vel Over Life", false },
//	{ "Initial Accel", false },
//	{ "Drag", false },
//	{ "Accel Over Life", false },
//	{ "Init Rotate", false },
//	{ "Rotate Over Life", false },
//	{ "Init Rot Rate", false },
//	{ "Rot Rate Life", false },
//	{ "Init Location", false },
//	{ "World Offset", false },
//	{ "Direct Location", false },
//	{ "Emitter Init Loc", false },
//	{ "Emitter Direct Loc", false },
//	{ "Sphere", false },
//	{ "Triangle", false },
//	{ "Sub UV", false },
//	{ "Orbit", false },
//	{ "Point Attractor", false },
//	{ "Line Attractor", false },
//	{ "Kill Box", false },
//	{ "Kill Height", false },
//	{ "Collision Floor", false },
//	{ "Collision Line", false },
//	{ "Collision Rect", false },
//	{ "Collision Sphere", false },
//};

//json configData = {
//	{"m_currentIndex", 0},
//	{"m_particleCount", 0},
//	{"m_particleNum", 10},
//	{"m_elapsed", 0},
//	{"m_elapsedDraw", 0},
//	{"m_emitCount", 0},
//	{"m_loopCount", 0},
//	{"m_isVisible", true},
//	{"m_locEmitter", NULL},
//	{"m_emitterLifeRate", 0},
//
//	//emitter and defalut modules' attri
//	{"m_texturePath", ""},
//	{"m_emitterName", "Emitter"},
//	{"m_emitterPosX", 0},
//	{"m_emitterPosY", 0},
//	{"m_emitterRot", 0},
//	{"m_killOnComplete", false},
//	{"m_killOnDeactivate", true},
//	{"m_useRange", false},
//	{"m_loop", 0},
//	{"m_durationRecal", false},
//	{"m_delay", 500},
//	{"m_delayLow", 0},
//	{"m_delayUseRange", false},
//	{"m_delayFirstLoop", false},
//	{"m_maxCount", 0},
//	{"m_countUseMax", false},
//	{"m_flipUV", 0},
//	{"m_flipTexcoordU", false},
//	{"m_flipTexcoordV", false},
//	{"m_randomTexU", false},
//	{"m_randomTexV", false},
//	{"m_subUVHori", 1},
//	{"m_subUVVerti", 1},
//	{"m_subUVMode", 0},
//	{"m_subUVRandomNum", 1},
//	{"m_brustNum", 0},
//	{"m_brustNumLow", -1},
//	{"m_brustTiming", 0},
//	{"m_useBrust", true},
//
//	//modules's attri
//	{"m_speedSizeX", 1},
//	{"m_speedSizeY", 1},
//	{"m_speedSizeXMax", 0},
//	{"m_speedSizeYMax", 0},
//	{"m_clampAlpha", false},
//	{"m_clampAlphaLife", false},
//	{"m_colorScaleEmitterLife", false},
//	{"m_coneDirection", 0},
//	{"m_velocityAbsolute", false},
//	{"m_locDistriPoint", 0},
//	{"m_locDistriThreshold", 0},
//	{"m_worldOffsetPoint", 0},
//	{"m_worldOffsetThreshold", 0},
//	{"m_locEmitterName", ""},
//	{"m_locEmitterMode", 0},
//	{"m_locEmitterCount", 0},
//	{"m_inheritSourceVelocity", false},
//	{"m_inheritSourceRotation", false},
//	{"m_inheritVelScale", 1},
//	{"m_inheritRotScale", 1},
//	{"m_locDirectEmitterName", ""},
//	{"m_spherePositiveX", true},
//	{"m_sphereNegativeX", true},
//	{"m_spherePositiveY", true},
//	{"m_sphereNegativeY", true},
//	{"m_sphereSurface", false},
//	{"m_sphereVelocity", false},
//	{"m_orbitOffsetSpawn", false},
//	{"m_orbitOffsetUpdate", false},
//	{"m_orbitOffsetEmitterTime", false},
//	{"m_orbitRotationSpawn", false},
//	{"m_orbitRotationUpdate", false},
//	{"m_orbitRotationEmitterTime", false},
//	{"m_orbitRotationRateSpawn", false},
//	{"m_orbitRotationRateUpdate", false},
//	{"m_orbitRotationRateEmitterTime", false},
//	{"m_strengthByDistance", false},
//	{"m_affectBaseVelocity", false },
//	{"m_lineAttractorPoint1X", 0},
//	{"m_lineAttractorPoint1Y", 0},
//	{"m_lineAttractorPoint2X", 0},
//	{"m_lineAttractorPoint2Y", 0},
//	{"m_killInside", false},
//	{"m_killFloor", true},
//	{"m_floorCollisionAxis", 0},
//	{"m_floorCollisionAxisPos", 0},
//	{"m_floorCollisionDelayAmount", 0},
//	{"m_floorCollisionCompleteOpt", 0},
//	{"m_lineCollisionPoint0X", 0},
//	{"m_lineCollisionPoint0Y", 0},
//	{"m_lineCollisionPoint1X", 0},
//	{"m_lineCollisionPoint1Y", 0},
//	{"m_lineCollisionDelayAmount", 0},
//	{"m_lineCollisionCompleteOpt", 0},
//	{"m_rectCollisionPosX", 0},
//	{"m_rectCollisionPosY", 0},
//	{"m_rectCollisionWidth", 0},
//	{"m_rectCollisionHeight", 0},
//	{"m_rectCollisionDelayAmount", 0},
//	{"m_rectCollisionCompleteOpt", 0},
//	{"m_sphereCollisionCenterX", 0},
//	{"m_sphereCollisionCenterY", 0},
//	{"m_sphereCollisionRadius", 0},
//	{"m_sphereCollisionDelayAmount", 0},
//	{"m_sphereCollisionCompleteOpt", 0},
//	{"m_duration", 3000},
//	{"m_durationLow", 0},
//	
//};

//json attributeFormat = {
//	{"pinAttribute" , false},
//	{"sizeAttribute" , false},
//	{"colorAttribute" , false},
//	{"flipAttribute" , false},
//	{"rotationAttribute" , false},
//	{"subUVAttribute" , false},
//	{"subUVBlendAttribute" , false},
//};